### ISSUE TITLE
Provided Gerber does not match Altium Data 

### ISSUE THREAD

**Issue by cad435** [SasaKaranovic/winfidel-sensor#1]
through sheer coincidence I just found out:

Just an example:

Gerber Data
![image](https://github.com/SasaKaranovic/winfidel-sensor/assets/16453385/207ee554-22f3-4c2c-a99d-8d48c758e29a)

Altium Data:
![image](https://github.com/SasaKaranovic/winfidel-sensor/assets/16453385/98c3eb3e-4886-40dc-9586-055343b2a79c)

**Comment by SasaKaranovic** [comment]
Thanks for mentioning this! I have just exported another gerber release that contains latest design. So everything should be good to go now.

If you look at the Gerbers, the silkscreen says "2023-DEC" but the Altium files have "2024-FEB".
This release was "rushed" in order to make sure people have all the source files available before Stefan's video goes live.
